name: flutter_keyboard_visibility_web
publish_to: none
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 2.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPluginWeb
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: 
    git: https://github.com/kumsumit/flutter_keyboard_visibility_platform_interface.git
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  web: ^1.1.1   

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter